---
- name: Add Docker's official GPG key
  block:
    - name: install ca-certificates and curl
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
    - name: Create keyring
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755
        owner: root
        group: root
    - name: Install GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    # - name: Set permissions
    #   ansible.builtin.file:
    #     path: /etc/apt/keyrings/docker.asc
    #     mode: a+r

- name: Add the repository to Apt sources
  block:
  
    - name: set fact UBUNTU_CODENAME
      ansible.builtin.set_fact:
        ubuntu_codename: "{{ ansible_distribution_release }}"
      tags: always

    - name: write apt sources file
      ansible.builtin.copy:
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: {{ ubuntu_codename }}
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc
        dest: /etc/apt/sources.list.d/docker.sources
        owner: root
        group: root
        mode: '0644'

- name: Install Docker
  block:
    - name: install docker
      ansible.builtin.apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present  
        update_cache: yes
    - name: restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: yes


        
        
  
